# Generated by Django 6.0.2 on 2026-02-26 14:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalContract",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "numero_contrat",
                    models.CharField(
                        db_index=True,
                        help_text="Format ex: 0001/26",
                        max_length=30,
                        verbose_name="Référence contrat",
                    ),
                ),
                (
                    "date_contrat",
                    models.DateField(db_index=True, verbose_name="Date du contrat"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Brouillon", "Brouillon"),
                            ("Envoyé", "Envoyé"),
                            ("Signé", "Signé"),
                            ("En cours", "En cours"),
                            ("Terminé", "Terminé"),
                            ("Annulé", "Annulé"),
                            ("Expiré", "Expiré"),
                        ],
                        db_index=True,
                        default="Brouillon",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "client_nom",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nom & Prénom",
                    ),
                ),
                (
                    "client_cin",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="CIN / ICE / Passeport",
                    ),
                ),
                (
                    "client_qualite",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("particulier", "Particulier"),
                            ("entreprise_societe", "Entreprise / Société"),
                            ("investisseur_immobilier", "Investisseur Immobilier"),
                            (
                                "administration_institution",
                                "Administration / Institution",
                            ),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Qualité du client",
                    ),
                ),
                (
                    "client_adresse",
                    models.TextField(
                        blank=True, null=True, verbose_name="Adresse complète"
                    ),
                ),
                (
                    "client_tel",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "ville_signature",
                    models.CharField(
                        default="Tanger",
                        max_length=100,
                        verbose_name="Ville de signature",
                    ),
                ),
                (
                    "adresse_travaux",
                    models.TextField(
                        blank=True, null=True, verbose_name="Adresse des travaux"
                    ),
                ),
                (
                    "type_bien",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("appartement", "Appartement"),
                            ("villa", "Villa"),
                            (
                                "riad_maison_traditionnelle",
                                "Riad / Maison Traditionnelle",
                            ),
                            ("bureau_local_commercial", "Bureau / Local Commercial"),
                            ("hotel_riad_hotelier", "Hôtel / Riad Hôtelier"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Type de bien",
                    ),
                ),
                (
                    "surface",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Surface (m²)",
                    ),
                ),
                (
                    "services",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Services sélectionnés"
                    ),
                ),
                (
                    "description_travaux",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description des travaux"
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début prévue"
                    ),
                ),
                (
                    "duree_estimee",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Durée estimée",
                    ),
                ),
                (
                    "conditions_acces",
                    models.TextField(
                        blank=True, null=True, verbose_name="Conditions d'accès"
                    ),
                ),
                (
                    "montant_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Montant total HT",
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        choices=[
                            ("MAD", "MAD – Dirham Marocain"),
                            ("EUR", "EUR – Euro"),
                            ("USD", "USD – Dollar Américain"),
                        ],
                        default="MAD",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=5,
                        verbose_name="TVA (%)",
                    ),
                ),
                (
                    "tranches",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste de {label, pourcentage}",
                        verbose_name="Échéancier de paiement",
                    ),
                ),
                (
                    "mode_paiement_texte",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Virement Bancaire", "Virement Bancaire"),
                            ("Chèque Certifié", "Chèque Certifié"),
                            ("Espèces", "Espèces"),
                            ("Paiement Mixte", "Paiement Mixte"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "rib",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="RIB / Coordonnées bancaires",
                    ),
                ),
                (
                    "delai_retard",
                    models.IntegerField(
                        default=5, verbose_name="Délai retard toléré (jours)"
                    ),
                ),
                (
                    "penalite_retard",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        max_digits=5,
                        verbose_name="Pénalité retard (%/j)",
                    ),
                ),
                (
                    "frais_redemarrage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Frais de redémarrage (MAD)",
                    ),
                ),
                (
                    "garantie",
                    models.CharField(
                        choices=[
                            ("6 mois", "6 mois"),
                            ("1 an", "1 an"),
                            ("2 ans", "2 ans"),
                            ("3 ans", "3 ans"),
                            ("sans_garantie", "Sans garantie contractuelle"),
                        ],
                        default="1 an",
                        max_length=50,
                        verbose_name="Durée de garantie",
                    ),
                ),
                (
                    "delai_reserves",
                    models.IntegerField(
                        default=7, verbose_name="Délai réserves (j ouvrés)"
                    ),
                ),
                (
                    "tribunal",
                    models.CharField(
                        choices=[
                            ("Tanger", "Tanger"),
                            ("Casablanca", "Casablanca"),
                            ("Rabat", "Rabat"),
                            ("Marrakech", "Marrakech"),
                            ("Fès", "Fès"),
                            ("Agadir", "Agadir"),
                        ],
                        default="Tanger",
                        max_length=50,
                        verbose_name="Tribunal compétent",
                    ),
                ),
                (
                    "clauses_actives",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Clauses actives"
                    ),
                ),
                (
                    "clause_spec",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Clauses spécifiques additionnelles",
                    ),
                ),
                (
                    "exclusions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Exclusions explicites"
                    ),
                ),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[
                            ("travaux_finition", "Travaux de Finition"),
                            ("travaux_gros_oeuvre", "Travaux Gros Œuvre"),
                            ("design_interieur", "Design Intérieur"),
                            ("cle_en_main", "Clé en Main"),
                            ("ameublement", "Ameublement"),
                            ("maintenance", "Maintenance"),
                            ("suivi_chantier", "Suivi Chantier"),
                        ],
                        default="travaux_finition",
                        max_length=50,
                        verbose_name="Type de contrat",
                    ),
                ),
                (
                    "responsable_projet",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Responsable de projet CASA DI LUSSO",
                    ),
                ),
                (
                    "architecte",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Architecte / Designer associé",
                    ),
                ),
                (
                    "confidentialite",
                    models.CharField(
                        choices=[
                            ("CONFIDENTIEL", "CONFIDENTIEL"),
                            ("USAGE INTERNE", "USAGE INTERNE"),
                            ("STANDARD", "STANDARD"),
                        ],
                        default="CONFIDENTIEL",
                        max_length=30,
                        verbose_name="Note de confidentialité",
                    ),
                ),
                (
                    "version_document",
                    models.CharField(
                        default="v1.0 – Définitif",
                        max_length=50,
                        verbose_name="Version du document",
                    ),
                ),
                (
                    "annexes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Annexes jointes"
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, editable=False)),
                ("date_updated", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Contrat",
                "verbose_name_plural": "historical Contrats",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_contrat",
                    models.CharField(
                        help_text="Format ex: 0001/26",
                        max_length=30,
                        unique=True,
                        verbose_name="Référence contrat",
                    ),
                ),
                (
                    "date_contrat",
                    models.DateField(db_index=True, verbose_name="Date du contrat"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Brouillon", "Brouillon"),
                            ("Envoyé", "Envoyé"),
                            ("Signé", "Signé"),
                            ("En cours", "En cours"),
                            ("Terminé", "Terminé"),
                            ("Annulé", "Annulé"),
                            ("Expiré", "Expiré"),
                        ],
                        db_index=True,
                        default="Brouillon",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "client_nom",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nom & Prénom",
                    ),
                ),
                (
                    "client_cin",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="CIN / ICE / Passeport",
                    ),
                ),
                (
                    "client_qualite",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("particulier", "Particulier"),
                            ("entreprise_societe", "Entreprise / Société"),
                            ("investisseur_immobilier", "Investisseur Immobilier"),
                            (
                                "administration_institution",
                                "Administration / Institution",
                            ),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Qualité du client",
                    ),
                ),
                (
                    "client_adresse",
                    models.TextField(
                        blank=True, null=True, verbose_name="Adresse complète"
                    ),
                ),
                (
                    "client_tel",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "ville_signature",
                    models.CharField(
                        default="Tanger",
                        max_length=100,
                        verbose_name="Ville de signature",
                    ),
                ),
                (
                    "adresse_travaux",
                    models.TextField(
                        blank=True, null=True, verbose_name="Adresse des travaux"
                    ),
                ),
                (
                    "type_bien",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("appartement", "Appartement"),
                            ("villa", "Villa"),
                            (
                                "riad_maison_traditionnelle",
                                "Riad / Maison Traditionnelle",
                            ),
                            ("bureau_local_commercial", "Bureau / Local Commercial"),
                            ("hotel_riad_hotelier", "Hôtel / Riad Hôtelier"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Type de bien",
                    ),
                ),
                (
                    "surface",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Surface (m²)",
                    ),
                ),
                (
                    "services",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Services sélectionnés"
                    ),
                ),
                (
                    "description_travaux",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description des travaux"
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début prévue"
                    ),
                ),
                (
                    "duree_estimee",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Durée estimée",
                    ),
                ),
                (
                    "conditions_acces",
                    models.TextField(
                        blank=True, null=True, verbose_name="Conditions d'accès"
                    ),
                ),
                (
                    "montant_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Montant total HT",
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        choices=[
                            ("MAD", "MAD – Dirham Marocain"),
                            ("EUR", "EUR – Euro"),
                            ("USD", "USD – Dollar Américain"),
                        ],
                        default="MAD",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=5,
                        verbose_name="TVA (%)",
                    ),
                ),
                (
                    "tranches",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste de {label, pourcentage}",
                        verbose_name="Échéancier de paiement",
                    ),
                ),
                (
                    "mode_paiement_texte",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Virement Bancaire", "Virement Bancaire"),
                            ("Chèque Certifié", "Chèque Certifié"),
                            ("Espèces", "Espèces"),
                            ("Paiement Mixte", "Paiement Mixte"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "rib",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="RIB / Coordonnées bancaires",
                    ),
                ),
                (
                    "delai_retard",
                    models.IntegerField(
                        default=5, verbose_name="Délai retard toléré (jours)"
                    ),
                ),
                (
                    "penalite_retard",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        max_digits=5,
                        verbose_name="Pénalité retard (%/j)",
                    ),
                ),
                (
                    "frais_redemarrage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Frais de redémarrage (MAD)",
                    ),
                ),
                (
                    "garantie",
                    models.CharField(
                        choices=[
                            ("6 mois", "6 mois"),
                            ("1 an", "1 an"),
                            ("2 ans", "2 ans"),
                            ("3 ans", "3 ans"),
                            ("sans_garantie", "Sans garantie contractuelle"),
                        ],
                        default="1 an",
                        max_length=50,
                        verbose_name="Durée de garantie",
                    ),
                ),
                (
                    "delai_reserves",
                    models.IntegerField(
                        default=7, verbose_name="Délai réserves (j ouvrés)"
                    ),
                ),
                (
                    "tribunal",
                    models.CharField(
                        choices=[
                            ("Tanger", "Tanger"),
                            ("Casablanca", "Casablanca"),
                            ("Rabat", "Rabat"),
                            ("Marrakech", "Marrakech"),
                            ("Fès", "Fès"),
                            ("Agadir", "Agadir"),
                        ],
                        default="Tanger",
                        max_length=50,
                        verbose_name="Tribunal compétent",
                    ),
                ),
                (
                    "clauses_actives",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Clauses actives"
                    ),
                ),
                (
                    "clause_spec",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Clauses spécifiques additionnelles",
                    ),
                ),
                (
                    "exclusions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Exclusions explicites"
                    ),
                ),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[
                            ("travaux_finition", "Travaux de Finition"),
                            ("travaux_gros_oeuvre", "Travaux Gros Œuvre"),
                            ("design_interieur", "Design Intérieur"),
                            ("cle_en_main", "Clé en Main"),
                            ("ameublement", "Ameublement"),
                            ("maintenance", "Maintenance"),
                            ("suivi_chantier", "Suivi Chantier"),
                        ],
                        default="travaux_finition",
                        max_length=50,
                        verbose_name="Type de contrat",
                    ),
                ),
                (
                    "responsable_projet",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Responsable de projet CASA DI LUSSO",
                    ),
                ),
                (
                    "architecte",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Architecte / Designer associé",
                    ),
                ),
                (
                    "confidentialite",
                    models.CharField(
                        choices=[
                            ("CONFIDENTIEL", "CONFIDENTIEL"),
                            ("USAGE INTERNE", "USAGE INTERNE"),
                            ("STANDARD", "STANDARD"),
                        ],
                        default="CONFIDENTIEL",
                        max_length=30,
                        verbose_name="Note de confidentialité",
                    ),
                ),
                (
                    "version_document",
                    models.CharField(
                        default="v1.0 – Définitif",
                        max_length=50,
                        verbose_name="Version du document",
                    ),
                ),
                (
                    "annexes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Annexes jointes"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrat",
                "verbose_name_plural": "Contrats",
                "ordering": ("-date_created",),
                "indexes": [
                    models.Index(
                        fields=["date_contrat"], name="contract_co_date_co_3be36d_idx"
                    ),
                    models.Index(
                        fields=["statut"], name="contract_co_statut_7b8f84_idx"
                    ),
                ],
            },
        ),
    ]
