# Generated by Django 6.0.2 on 2026-03-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="acompte",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Acompte (%)",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="chantier_etage",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Étage / Appartement",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="chantier_ville",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ville du chantier"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="clause_resiliation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("30j", "Préavis de 30 jours"),
                    ("15j", "Préavis de 15 jours"),
                    ("mutuel", "D'un commun accord"),
                    ("aucune", "Aucune clause"),
                ],
                max_length=50,
                null=True,
                verbose_name="Clause de résiliation",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="client_cp",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Code postal client"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="client_ville",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ville du client"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="company",
            field=models.CharField(
                choices=[
                    ("casa_di_lusso", "Casa di Lusso"),
                    ("blueline_works", "Blueline Works"),
                ],
                db_index=True,
                default="casa_di_lusso",
                max_length=50,
                verbose_name="Société",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="eau_electricite",
            field=models.CharField(
                blank=True,
                choices=[
                    ("client", "À la charge du client"),
                    ("entreprise", "À la charge de l'entreprise"),
                    ("partage", "Partagé"),
                    ("selon_cas", "Selon le cas"),
                ],
                max_length=50,
                null=True,
                verbose_name="Eau & Électricité sur chantier",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="exclusions_garantie",
            field=models.TextField(
                blank=True, null=True, verbose_name="Exclusions de garantie"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="fournitures",
            field=models.CharField(
                blank=True,
                choices=[
                    ("non_incluses", "Non incluses (fournies par le client)"),
                    ("incluses", "Incluses dans le contrat"),
                    ("partielles", "Partiellement incluses"),
                ],
                max_length=50,
                null=True,
                verbose_name="Fournitures incluses",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="garantie_nb",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Durée de garantie (valeur)"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="garantie_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("defauts", "Garantie des défauts"),
                    ("bonne_fin", "Garantie de bonne fin"),
                    ("decennale", "Garantie décennale"),
                    ("aucune", "Aucune garantie"),
                ],
                max_length=50,
                null=True,
                verbose_name="Type de garantie",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="garantie_unite",
            field=models.CharField(
                blank=True,
                choices=[("mois", "Mois"), ("ans", "Ans")],
                max_length=10,
                null=True,
                verbose_name="Unité de garantie",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="materiaux_detail",
            field=models.TextField(
                blank=True, null=True, verbose_name="Matériaux à fournir par le client"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Notes & Observations"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="prestations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste de {nom, desc, qte, unite, pu}",
                verbose_name="Prestations",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="tranche2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="2ème tranche (%)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="acompte",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Acompte (%)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="chantier_etage",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Étage / Appartement",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="chantier_ville",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ville du chantier"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="clause_resiliation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("30j", "Préavis de 30 jours"),
                    ("15j", "Préavis de 15 jours"),
                    ("mutuel", "D'un commun accord"),
                    ("aucune", "Aucune clause"),
                ],
                max_length=50,
                null=True,
                verbose_name="Clause de résiliation",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="client_cp",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Code postal client"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="client_ville",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ville du client"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="company",
            field=models.CharField(
                choices=[
                    ("casa_di_lusso", "Casa di Lusso"),
                    ("blueline_works", "Blueline Works"),
                ],
                db_index=True,
                default="casa_di_lusso",
                max_length=50,
                verbose_name="Société",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="eau_electricite",
            field=models.CharField(
                blank=True,
                choices=[
                    ("client", "À la charge du client"),
                    ("entreprise", "À la charge de l'entreprise"),
                    ("partage", "Partagé"),
                    ("selon_cas", "Selon le cas"),
                ],
                max_length=50,
                null=True,
                verbose_name="Eau & Électricité sur chantier",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="exclusions_garantie",
            field=models.TextField(
                blank=True, null=True, verbose_name="Exclusions de garantie"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="fournitures",
            field=models.CharField(
                blank=True,
                choices=[
                    ("non_incluses", "Non incluses (fournies par le client)"),
                    ("incluses", "Incluses dans le contrat"),
                    ("partielles", "Partiellement incluses"),
                ],
                max_length=50,
                null=True,
                verbose_name="Fournitures incluses",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="garantie_nb",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Durée de garantie (valeur)"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="garantie_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("defauts", "Garantie des défauts"),
                    ("bonne_fin", "Garantie de bonne fin"),
                    ("decennale", "Garantie décennale"),
                    ("aucune", "Aucune garantie"),
                ],
                max_length=50,
                null=True,
                verbose_name="Type de garantie",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="garantie_unite",
            field=models.CharField(
                blank=True,
                choices=[("mois", "Mois"), ("ans", "Ans")],
                max_length=10,
                null=True,
                verbose_name="Unité de garantie",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="materiaux_detail",
            field=models.TextField(
                blank=True, null=True, verbose_name="Matériaux à fournir par le client"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Notes & Observations"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="prestations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste de {nom, desc, qte, unite, pu}",
                verbose_name="Prestations",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="tranche2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="2ème tranche (%)",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="mode_paiement_texte",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Virement Bancaire", "Virement Bancaire"),
                    ("Chèque Certifié", "Chèque Certifié"),
                    ("Espèces", "Espèces"),
                    ("Paiement Mixte", "Paiement Mixte"),
                    ("Mobile Money", "Mobile Money"),
                    ("Virement ou Chèque", "Virement ou Chèque"),
                ],
                max_length=100,
                null=True,
                verbose_name="Mode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="type_bien",
            field=models.CharField(
                blank=True,
                choices=[
                    ("appartement", "Appartement"),
                    ("villa", "Villa"),
                    ("duplex", "Duplex"),
                    ("riad_maison_traditionnelle", "Riad / Maison Traditionnelle"),
                    ("bureau_local_commercial", "Bureau / Local Commercial"),
                    ("commerce_local", "Commerce / Local"),
                    ("hotel_riad_hotelier", "Hôtel / Riad Hôtelier"),
                    ("immeuble", "Immeuble"),
                    ("autre", "Autre"),
                ],
                max_length=50,
                null=True,
                verbose_name="Type de bien",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="mode_paiement_texte",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Virement Bancaire", "Virement Bancaire"),
                    ("Chèque Certifié", "Chèque Certifié"),
                    ("Espèces", "Espèces"),
                    ("Paiement Mixte", "Paiement Mixte"),
                    ("Mobile Money", "Mobile Money"),
                    ("Virement ou Chèque", "Virement ou Chèque"),
                ],
                max_length=100,
                null=True,
                verbose_name="Mode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="type_bien",
            field=models.CharField(
                blank=True,
                choices=[
                    ("appartement", "Appartement"),
                    ("villa", "Villa"),
                    ("duplex", "Duplex"),
                    ("riad_maison_traditionnelle", "Riad / Maison Traditionnelle"),
                    ("bureau_local_commercial", "Bureau / Local Commercial"),
                    ("commerce_local", "Commerce / Local"),
                    ("hotel_riad_hotelier", "Hôtel / Riad Hôtelier"),
                    ("immeuble", "Immeuble"),
                    ("autre", "Autre"),
                ],
                max_length=50,
                null=True,
                verbose_name="Type de bien",
            ),
        ),
    ]
