# Generated by Django 6.0.2 on 2026-03-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0002_add_company_and_blueline_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="numero_contrat",
            field=models.CharField(
                help_text="Format ex: 0001/26",
                max_length=30,
                verbose_name="Référence contrat",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="numero_contrat",
            field=models.CharField(
                help_text="Format ex: 0001/26",
                max_length=30,
                verbose_name="Référence contrat",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contract",
            unique_together={("company", "numero_contrat")},
        ),
    ]
