# Generated by Django 6.0.3 on 2026-03-05 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0003_numero_contrat_unique_per_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contract",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_category",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("sous_traitance", "Sous-Traitance"),
                ],
                db_index=True,
                default="standard",
                max_length=30,
                verbose_name="Catégorie de contrat",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_addr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Adresse siège ST"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_avance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Avance forfaitaire (%)",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_banque",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Banque ST"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_capital",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Capital social ST",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_cin",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="CIN représentant ST"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_clauses_actives",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Clauses actives ST"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_cnss",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="CNSS ST"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_delai_med",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Délai médiation (jours)"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_delai_paiement",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Délai de paiement (jours)"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_delai_reserves",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Délai levée réserves (jours)"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_delai_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mois", "Mois"),
                    ("semaines", "Semaines"),
                    ("jours", "Jours"),
                ],
                max_length=20,
                null=True,
                verbose_name="Unité délai d'exécution",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_delai_val",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Délai d'exécution (valeur)"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email ST"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_forme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SARL", "SARL"),
                    ("SA", "SA"),
                    ("SARLAU", "SARLAU"),
                    ("SNC", "SNC"),
                    ("auto_entrepreneur", "Auto-entrepreneur"),
                    ("personne_physique", "Personne physique"),
                ],
                max_length=50,
                null=True,
                verbose_name="Forme juridique ST",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_garantie_mois",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Garantie décennale (mois)"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_ice",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ICE ST"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_if",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Identifiant fiscal ST",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_lot_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description du lot"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_lot_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gros_oeuvre", "Travaux de Gros Œuvre"),
                    ("electricite", "Travaux d'Électricité"),
                    ("plomberie", "Travaux de Plomberie et Sanitaire"),
                    ("menuiserie_alu", "Travaux de Menuiserie Aluminium"),
                    ("menuiserie_bois", "Travaux de Menuiserie Bois"),
                    ("carrelage", "Travaux de Carrelage et Faïence"),
                    ("peinture", "Travaux de Peinture"),
                    ("etancheite", "Travaux d'Étanchéité"),
                    ("ascenseur", "Fourniture et Installation d'Ascenseur"),
                    ("platre", "Travaux de Plâtre et Faux Plafond"),
                    ("ferronnerie", "Travaux de Ferronnerie et Garde-Corps"),
                    ("vrd", "Travaux de VRD et Façade"),
                    ("climatisation", "Travaux de Climatisation et Ventilation"),
                    ("cuisine", "Fourniture et Pose de Cuisines Équipées"),
                ],
                max_length=50,
                null=True,
                verbose_name="Type de lot",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_name",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Raison sociale ST"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_observations",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observations ST"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_penalite_taux",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Pénalité retard (‰/jour)",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_plafond_penalite",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Plafond pénalité (%)",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_qualite",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Qualité représentant ST",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_rc",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="RC ST"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_rep",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Représentant ST"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_retenue_garantie",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Retenue de garantie (%)",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_rib",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="RIB ST"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_tel",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Téléphone ST"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_tranches",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{label, pourcentage}]",
                verbose_name="Tranches paiement ST",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="st_type_prix",
            field=models.CharField(
                blank=True,
                choices=[
                    ("forfaitaire", "Forfaitaire ferme"),
                    ("unitaire", "Prix unitaires"),
                    ("regie", "Régie"),
                ],
                max_length=30,
                null=True,
                verbose_name="Type de prix",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="contract_category",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("sous_traitance", "Sous-Traitance"),
                ],
                db_index=True,
                default="standard",
                max_length=30,
                verbose_name="Catégorie de contrat",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_addr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Adresse siège ST"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_avance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Avance forfaitaire (%)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_banque",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Banque ST"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_capital",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Capital social ST",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_cin",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="CIN représentant ST"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_clauses_actives",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Clauses actives ST"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_cnss",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="CNSS ST"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_delai_med",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Délai médiation (jours)"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_delai_paiement",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Délai de paiement (jours)"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_delai_reserves",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Délai levée réserves (jours)"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_delai_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mois", "Mois"),
                    ("semaines", "Semaines"),
                    ("jours", "Jours"),
                ],
                max_length=20,
                null=True,
                verbose_name="Unité délai d'exécution",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_delai_val",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Délai d'exécution (valeur)"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email ST"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_forme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SARL", "SARL"),
                    ("SA", "SA"),
                    ("SARLAU", "SARLAU"),
                    ("SNC", "SNC"),
                    ("auto_entrepreneur", "Auto-entrepreneur"),
                    ("personne_physique", "Personne physique"),
                ],
                max_length=50,
                null=True,
                verbose_name="Forme juridique ST",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_garantie_mois",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Garantie décennale (mois)"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_ice",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ICE ST"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_if",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Identifiant fiscal ST",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_lot_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description du lot"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_lot_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gros_oeuvre", "Travaux de Gros Œuvre"),
                    ("electricite", "Travaux d'Électricité"),
                    ("plomberie", "Travaux de Plomberie et Sanitaire"),
                    ("menuiserie_alu", "Travaux de Menuiserie Aluminium"),
                    ("menuiserie_bois", "Travaux de Menuiserie Bois"),
                    ("carrelage", "Travaux de Carrelage et Faïence"),
                    ("peinture", "Travaux de Peinture"),
                    ("etancheite", "Travaux d'Étanchéité"),
                    ("ascenseur", "Fourniture et Installation d'Ascenseur"),
                    ("platre", "Travaux de Plâtre et Faux Plafond"),
                    ("ferronnerie", "Travaux de Ferronnerie et Garde-Corps"),
                    ("vrd", "Travaux de VRD et Façade"),
                    ("climatisation", "Travaux de Climatisation et Ventilation"),
                    ("cuisine", "Fourniture et Pose de Cuisines Équipées"),
                ],
                max_length=50,
                null=True,
                verbose_name="Type de lot",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_name",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Raison sociale ST"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_observations",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observations ST"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_penalite_taux",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Pénalité retard (‰/jour)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_plafond_penalite",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Plafond pénalité (%)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_qualite",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Qualité représentant ST",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_rc",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="RC ST"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_rep",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Représentant ST"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_retenue_garantie",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Retenue de garantie (%)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_rib",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="RIB ST"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_tel",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Téléphone ST"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_tranches",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{label, pourcentage}]",
                verbose_name="Tranches paiement ST",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_type_prix",
            field=models.CharField(
                blank=True,
                choices=[
                    ("forfaitaire", "Forfaitaire ferme"),
                    ("unitaire", "Prix unitaires"),
                    ("regie", "Régie"),
                ],
                max_length=30,
                null=True,
                verbose_name="Type de prix",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contract",
            unique_together={("company", "contract_category", "numero_contrat")},
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        choices=[
                            ("casa_di_lusso", "Casa di Lusso"),
                            ("blueline_works", "Blueline Works"),
                        ],
                        db_index=True,
                        default="casa_di_lusso",
                        max_length=50,
                        verbose_name="Société",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=300, verbose_name="Nom du projet"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("immeuble", "Immeuble"),
                            ("villa", "Villa"),
                            ("commercial", "Commercial"),
                            ("industriel", "Industriel"),
                            ("renovation", "Rénovation"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Type de projet",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "adresse",
                    models.TextField(
                        blank=True, null=True, verbose_name="Adresse du projet"
                    ),
                ),
                (
                    "maitre_ouvrage",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Maître d'ouvrage",
                    ),
                ),
                (
                    "permis",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="N° permis de construire",
                    ),
                ),
                (
                    "is_predefined",
                    models.BooleanField(
                        default=False,
                        help_text="Prédéfini par l'admin, non supprimable par les utilisateurs.",
                        verbose_name="Prédéfini",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="st_projet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="contract.project",
                verbose_name="Projet",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="st_projet",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contract.project",
                verbose_name="Projet",
            ),
        ),
    ]
