# Generated by Django 6.0.3 on 2026-03-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0005_alter_contract_penalite_retard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="garantie",
            field=models.CharField(
                choices=[
                    ("1 mois", "1 mois"),
                    ("3 mois", "3 mois"),
                    ("6 mois", "6 mois"),
                    ("1 an", "1 an"),
                    ("2 ans", "2 ans"),
                    ("3 ans", "3 ans"),
                    ("sans_garantie", "Sans garantie contractuelle"),
                ],
                default="1 an",
                max_length=50,
                verbose_name="Durée de garantie",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="penalite_retard",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Pénalité retard (MAD/j)",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="st_delai_med",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Délai mise en demeure (jours)"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="type_bien",
            field=models.CharField(
                blank=True,
                choices=[
                    ("appartement", "Appartement"),
                    ("villa", "Villa"),
                    ("duplex", "Duplex"),
                    ("residence", "Résidence"),
                    ("hotel", "Hôtel"),
                    ("riad_maison_traditionnelle", "Riad / Maison Traditionnelle"),
                    ("bureau_local_commercial", "Bureau / Local Commercial"),
                    ("commerce_local", "Commerce / Local"),
                    ("hotel_riad_hotelier", "Hôtel / Riad Hôtelier"),
                    ("immeuble", "Immeuble"),
                    ("autre", "Autre"),
                ],
                max_length=50,
                null=True,
                verbose_name="Type de bien",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="garantie",
            field=models.CharField(
                choices=[
                    ("1 mois", "1 mois"),
                    ("3 mois", "3 mois"),
                    ("6 mois", "6 mois"),
                    ("1 an", "1 an"),
                    ("2 ans", "2 ans"),
                    ("3 ans", "3 ans"),
                    ("sans_garantie", "Sans garantie contractuelle"),
                ],
                default="1 an",
                max_length=50,
                verbose_name="Durée de garantie",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="penalite_retard",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Pénalité retard (MAD/j)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="st_delai_med",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Délai mise en demeure (jours)"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="type_bien",
            field=models.CharField(
                blank=True,
                choices=[
                    ("appartement", "Appartement"),
                    ("villa", "Villa"),
                    ("duplex", "Duplex"),
                    ("residence", "Résidence"),
                    ("hotel", "Hôtel"),
                    ("riad_maison_traditionnelle", "Riad / Maison Traditionnelle"),
                    ("bureau_local_commercial", "Bureau / Local Commercial"),
                    ("commerce_local", "Commerce / Local"),
                    ("hotel_riad_hotelier", "Hôtel / Riad Hôtelier"),
                    ("immeuble", "Immeuble"),
                    ("autre", "Autre"),
                ],
                max_length=50,
                null=True,
                verbose_name="Type de bien",
            ),
        ),
    ]
