# Generated by Django 6.0.3 on 2026-03-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("contract", "0007_alter_st_lot_type_st_type_prix_penalite"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE contract_historicalcontract
                SET st_lot_type = CASE
                    WHEN st_lot_type IS NULL OR st_lot_type = '' THEN '[]'
                    WHEN st_lot_type LIKE '[%' THEN st_lot_type
                    ELSE '["' || st_lot_type || '"]'
                END
                WHERE st_lot_type IS NULL OR st_lot_type NOT LIKE '[%';

                UPDATE contract_historicalcontract
                SET st_type_prix = CASE
                    WHEN st_type_prix IS NULL OR st_type_prix = '' THEN '[]'
                    WHEN st_type_prix LIKE '[%' THEN st_type_prix
                    ELSE '["' || st_type_prix || '"]'
                END
                WHERE st_type_prix IS NULL OR st_type_prix NOT LIKE '[%';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="st_lot_type",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Type(s) de lot"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="st_penalite_taux",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Pénalité retard (MAD/jour)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="st_type_prix",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Type(s) de prix"
            ),
        ),
    ]
