# Generated by Django 6.0.3 on 2026-03-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0008_alter_historicalcontract_st_lot_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="version_document",
        ),
        migrations.RemoveField(
            model_name="historicalcontract",
            name="version_document",
        ),
    ]
