# Generated by Django 6.0.3 on 2026-04-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0009_remove_version_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="st_tranches",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="{label, pourcentage}",
                verbose_name="Tranches paiement ST",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="tranches",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste de {label, pourcentage}",
                verbose_name="Echéancier de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="st_tranches",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="{label, pourcentage}",
                verbose_name="Tranches paiement ST",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="tranches",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste de {label, pourcentage}",
                verbose_name="Echéancier de paiement",
            ),
        ),
    ]
