# Generated by Django 6.0.3 on 2026-04-07 10:47

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contract",
            "0010_alter_contract_st_tranches_alter_contract_tranches_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalProject",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        choices=[
                            ("casa_di_lusso", "Casa di Lusso"),
                            ("blueline_works", "Blueline Works"),
                        ],
                        db_index=True,
                        default="casa_di_lusso",
                        max_length=50,
                        verbose_name="Société",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=300, verbose_name="Nom du projet"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("immeuble", "Immeuble"),
                            ("villa", "Villa"),
                            ("commercial", "Commercial"),
                            ("industriel", "Industriel"),
                            ("renovation", "Rénovation"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Type de projet",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "adresse",
                    models.TextField(
                        blank=True, null=True, verbose_name="Adresse du projet"
                    ),
                ),
                (
                    "maitre_ouvrage",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Maître d'ouvrage",
                    ),
                ),
                (
                    "permis",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="N° permis de construire",
                    ),
                ),
                (
                    "is_predefined",
                    models.BooleanField(
                        default=False,
                        help_text="Prédéfini par l'admin, non supprimable par les utilisateurs.",
                        verbose_name="Prédéfini",
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, editable=False)),
                ("date_updated", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Projet",
                "verbose_name_plural": "Historiques Projets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
