# Generated by Django 6.0.3 on 2026-03-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        choices=[
                            ("casa_di_lusso", "Casa di Lusso"),
                            ("blueline_works", "Blueline Works"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Société",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Raison sociale"),
                ),
                (
                    "forme_juridique",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Forme juridique",
                    ),
                ),
                (
                    "capital",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Capital (DH)",
                    ),
                ),
                (
                    "rc",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Registre de Commerce",
                    ),
                ),
                (
                    "ice",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="ICE"
                    ),
                ),
                (
                    "identifiant_fiscal",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Identifiant Fiscal (IF)",
                    ),
                ),
                (
                    "adresse",
                    models.TextField(
                        blank=True, default="", verbose_name="Adresse du siège social"
                    ),
                ),
                (
                    "representant",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Représentant légal",
                    ),
                ),
                (
                    "qualite_representant",
                    models.CharField(
                        default="Gérant",
                        max_length=100,
                        verbose_name="Qualité du représentant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration Société",
                "verbose_name_plural": "Configurations Sociétés",
            },
        ),
    ]
