# Generated by Django 6.0.3 on 2026-04-07 10:47

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCompanyConfig",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        choices=[
                            ("casa_di_lusso", "Casa di Lusso"),
                            ("blueline_works", "Blueline Works"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Société",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Raison sociale"),
                ),
                (
                    "forme_juridique",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Forme juridique",
                    ),
                ),
                (
                    "capital",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Capital (DH)",
                    ),
                ),
                (
                    "rc",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Registre de Commerce",
                    ),
                ),
                (
                    "ice",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="ICE"
                    ),
                ),
                (
                    "identifiant_fiscal",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Identifiant Fiscal (IF)",
                    ),
                ),
                (
                    "adresse",
                    models.TextField(
                        blank=True, default="", verbose_name="Adresse du siège social"
                    ),
                ),
                (
                    "representant",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Représentant légal",
                    ),
                ),
                (
                    "qualite_representant",
                    models.CharField(
                        default="Gérant",
                        max_length=100,
                        verbose_name="Qualité du représentant",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Configuration",
                "verbose_name_plural": "Historiques Configurations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
